"""Golden / snapshot tests for the deterministic rendering in ``tools``.

These pin the *structure* of the artifacts the action layer writes — ticket
Markdown, PR-draft Markdown, and the TRACKER ledger — so an accidental change
to a heading or column is caught in review. They assert on required sections and
fields rather than a byte-for-byte blob (the tracker embeds a timestamp).
"""

from __future__ import annotations

from pathlib import Path

import pytest

from autotriage import tools
from autotriage.schema import (
    Action,
    Finding,
    FindingType,
    ScannerTool,
    Severity,
    TriageDecision,
    Verdict,
)


@pytest.fixture
def golden_finding() -> Finding:
    """A fixed, fully-populated finding used across the golden tests."""
    return Finding(
        id="abc123def456",
        tool=ScannerTool.SEMGREP,
        type=FindingType.SAST,
        rule_id="python.lang.security.sql-injection",
        title="SQL injection via f-string in query",
        severity_raw="ERROR",
        cwe=["CWE-89"],
        owasp=["A03:2021"],
        file="target/app.py",
        line=44,
        code_snippet="cursor.execute(f\"SELECT * FROM users WHERE name = '{u}'\")",
        description="User input is interpolated into a SQL query.",
    )


@pytest.fixture
def golden_decision() -> TriageDecision:
    """A fixed high-confidence decision used across the golden tests."""
    return TriageDecision(
        finding_id="abc123def456",
        verdict=Verdict.TRUE_POSITIVE,
        severity=Severity.CRITICAL,
        confidence=0.93,
        business_impact="Attacker can exfiltrate the entire customer table.",
        reasoning="Untrusted username is interpolated straight into SQL.",
        recommended_action=Action.DRAFT_PR,
        suggested_owner="@app-team @alice",
        remediation="Use a parameterized query with bound parameters.",
        cwe=["CWE-89"],
    )


def test_file_ticket_golden_structure(
    golden_finding: Finding, golden_decision: TriageDecision, tmp_path: Path
) -> None:
    """A filed ticket contains every required heading and field."""
    ticket_path = tools.file_ticket(
        golden_finding,
        golden_decision,
        tickets_dir=tmp_path / "tickets",
        tracker_path=tmp_path / "TRACKER.md",
    )
    assert ticket_path == tmp_path / "tickets" / "abc123def456.md"
    text = ticket_path.read_text(encoding="utf-8")

    assert text.startswith("# [CRITICAL] SQL injection via f-string in query")
    for fragment in (
        "- **Finding ID:** abc123def456",
        "- **Scanner:** semgrep (SAST)",
        "- **Rule:** python.lang.security.sql-injection",
        "- **Location:** `target/app.py:44`",
        "- **CWE:** CWE-89",
        "- **Verdict:** true_positive",
        "- **Severity:** critical",
        "- **Confidence:** 0.93",
        "- **Recommended action:** draft_pr",
        "- **Owner:** @app-team @alice",
    ):
        assert fragment in text
    for section in (
        "## Business impact",
        "## Reasoning",
        "## Remediation",
        "## Offending code",
    ):
        assert section in text
    assert golden_decision.business_impact in text
    assert golden_decision.remediation in text
    assert golden_finding.code_snippet in text


def test_file_ticket_defaults_when_fields_empty(
    golden_finding: Finding, tmp_path: Path
) -> None:
    """Missing owner/remediation/cwe fall back to stable placeholders."""
    decision = TriageDecision(
        finding_id=golden_finding.id,
        verdict=Verdict.TRUE_POSITIVE,
        severity=Severity.HIGH,
        confidence=0.8,
        business_impact="impact",
        reasoning="reasoning",
        recommended_action=Action.OPEN_TICKET,
        suggested_owner=None,
        remediation="",
        cwe=[],
    )
    bare = golden_finding.model_copy(update={"cwe": []})
    ticket_path = tools.file_ticket(
        bare,
        decision,
        tickets_dir=tmp_path / "tickets",
        tracker_path=tmp_path / "TRACKER.md",
    )
    text = ticket_path.read_text(encoding="utf-8")
    assert "- **Owner:** unassigned" in text
    assert "- **CWE:** n/a" in text
    assert "remediation to be determined" in text


def test_draft_pr_golden_structure(
    golden_finding: Finding, golden_decision: TriageDecision, tmp_path: Path
) -> None:
    """A PR draft contains every required heading and field."""
    pr_path = tools.draft_pr(golden_finding, golden_decision, out_dir=tmp_path / "prs")
    assert pr_path == tmp_path / "prs" / "abc123def456.pr.md"
    text = pr_path.read_text(encoding="utf-8")

    assert text.startswith("# Fix: SQL injection via f-string in query")
    for fragment in (
        "_Automated remediation draft generated by AutoTriage._",
        "- **Finding ID:** abc123def456",
        "- **Location:** `target/app.py:44`",
        "- **Severity:** critical",
        "- **Suggested reviewer:** @app-team @alice",
        "## Why",
        "## Proposed change",
        "## Original code",
    ):
        assert fragment in text
    assert golden_decision.remediation in text


def test_draft_pr_default_remediation(golden_finding: Finding, tmp_path: Path) -> None:
    """An empty remediation falls back to the stable placeholder text."""
    decision = TriageDecision(
        finding_id=golden_finding.id,
        verdict=Verdict.TRUE_POSITIVE,
        severity=Severity.HIGH,
        confidence=0.8,
        business_impact="impact",
        reasoning="reasoning",
        recommended_action=Action.DRAFT_PR,
        remediation="",
    )
    text = tools.draft_pr(golden_finding, decision, out_dir=tmp_path / "prs").read_text(
        encoding="utf-8"
    )
    assert "No concrete remediation was provided" in text
    assert "- **Suggested reviewer:** unassigned" in text


def test_tracker_golden_structure(
    golden_finding: Finding, golden_decision: TriageDecision, tmp_path: Path
) -> None:
    """The tracker gets a header once and one aligned row per action."""
    tracker = tmp_path / "TRACKER.md"
    tools.file_ticket(
        golden_finding,
        golden_decision,
        tickets_dir=tmp_path / "tickets",
        tracker_path=tracker,
    )
    tools.escalate(golden_finding, golden_decision, tracker_path=tracker)
    text = tracker.read_text(encoding="utf-8")

    assert text.startswith("# AutoTriage Tracker")
    assert "| Timestamp (UTC) | Finding | Verdict | Severity | Confidence" in text
    separator = "| --- | --- | --- | --- | --- | --- | --- | --- |"
    assert text.count(separator) == 1  # header separator written exactly once

    rows = [
        ln
        for ln in text.splitlines()
        if ln.startswith("| ") and "| abc123def456 |" in ln
    ]
    assert len(rows) == 2
    # The ticket row carries the recommended action; the escalate row is tagged.
    assert any("draft_pr" in r for r in rows)
    assert any("escalate:human-review" in r for r in rows)
    for row in rows:
        # Eight data columns => nine pipes on a well-formed row.
        assert row.count("|") == 9
        assert "true_positive" in row
        assert "critical" in row
        assert "0.93" in row
